apiVersion: v1
kind: ConfigMap
metadata:
  name: cinemaabyss-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # Database configuration
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}

  # Service URLs
  MONOLITH_URL: "http://monolith:{{ .Values.monolith.service.port }}"
  MOVIES_SERVICE_URL: "http://movies:{{ .Values.moviesService.service.port }}"
  
  # Strangler Fig configuration
  GRADUAL_MIGRATION: {{ .Values.config.gradualMigration | quote }}
  MOVIES_MIGRATION_PERCENT: {{ .Values.config.moviesMigrationPercent | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinemaabyss-kafka
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  KAFKA_BROKER_ID: '1'
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
  KAFKA_CREATE_TOPICS: "movie-events:1:1,user-events:1:1,payment-events:1:1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_NODE_ID: '1'
  KAFKA_NUM_PARTITIONS: '3'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  PROCESS_ROLES: ''