{{- if .Values.eventsService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.eventsService.replicas }}
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: "{{ .Values.eventsService.image.repository }}:{{ .Values.eventsService.image.tag }}"
          imagePullPolicy: {{ .Values.eventsService.image.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.eventsService.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.eventsService.service.port }}"
          resources:
            limits:
              cpu: "{{ .Values.eventsService.resources.limits.cpu }}"
              memory: "{{ .Values.eventsService.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.eventsService.resources.requests.cpu }}"
              memory: "{{ .Values.eventsService.resources.requests.memory }}"
          readinessProbe:
            httpGet:
              path: "{{ .Values.eventsService.probes.readiness.path }}"
              port: {{ .Values.eventsService.service.port }}
            initialDelaySeconds: {{ .Values.eventsService.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.eventsService.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: "{{ .Values.eventsService.probes.liveness.path }}"
              port: {{ .Values.eventsService.service.port }}
            initialDelaySeconds: {{ .Values.eventsService.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.eventsService.probes.liveness.periodSeconds }}
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: events-service
  ports:
    - port: {{ .Values.eventsService.service.port }}
      targetPort: {{ .Values.eventsService.service.port }}
  type: {{ .Values.eventsService.service.type }}
{{- end }}